#  Copyright 2016-2018 Daniel Carbone (daniel.p.carbone@gmail.com)
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

services:

  # Default Consul config
  consul_api.local.config:
    class: 'DCarbone\PHPConsulAPI\Config'

  # Consul client using environment parameters
  consul_api.prototype:
    class: 'DCarbone\PHPConsulAPI\Consul'
    abstract: true

  consul_api.default_cache:
    class: 'Symfony\Component\Cache\Adapter\PhpFilesAdapter'
    lazy: true
    arguments:
      - 'consul_api'

  consul_api.default_cache_persister:
    class: 'DCarbone\PHPConsulAPIBundle\Cache\Persister'
    arguments:
    - '@consul_api.default_cache'

  consul_api.bag:
    class: 'DCarbone\PHPConsulAPIBundle\Bag\ConsulBag'

  consul_api.default_guzzle_client:
    class: 'GuzzleHttp\Client'

  consul_api.env_processor:
    class: 'DCarbone\PHPConsulAPIBundle\DependencyInjection\EnvVarProcessor'
    tags: ['container.env_var_processor']

  consul_api.twig.extension:
    class: 'DCarbone\PHPConsulAPIBundle\Twig\PHPConsulAPITwigExtension'
    arguments:
      - '@consul_api.bag'
    tags: ['twig.extension']