#  Copyright 2016 Daniel Carbone (daniel.p.carbone@gmail.com)
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

services:

    # Default Consul config
    consul_api.local.config:
        class: DCarbone\PHPConsulAPI\Config
        factory: [DCarbone\PHPConsulAPI\Config, newDefaultConfig]

    # Consul client using environment parameters
    consul_api.local:
        class: DCarbone\PHPConsulAPI\Consul

    consul_api.bag:
        class: DCarbone\PHPConsulAPIBundle\Bag\ConsulBag
        arguments:
            - "@consul_api.local"